# Generated by Django 2.1.5 on 2019-03-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=255)),
                ('noticeTitle', models.CharField(max_length=255)),
                ('noticeSubject', models.TextField(blank=True, null=True)),
                ('noticePdf', models.FileField(upload_to='notice/')),
                ('noticUrl', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
