# Generated by Django 2.1.5 on 2019-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teachernotice_noticepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachernotice',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
