# Generated by Django 2.1.5 on 2019-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190321_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotices',
            fields=[
                ('teacherName', models.CharField(max_length=255)),
                ('noticeTitle', models.CharField(max_length=255)),
                ('noticeSubject', models.TextField(blank=True, null=True)),
                ('noticUrl', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
